// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: store_item.sql

package testapp

import (
	"context"
)

const storeItemCreate = `-- name: StoreItemCreate :exec
INSERT INTO goweb.stores_items (
  store_id, item_id
) VALUES (
  ?, ?
)
`

type StoreItemCreateParams struct {
	StoreID uint32
	ItemID  uint32
}

func (q *Queries) StoreItemCreate(ctx context.Context, arg StoreItemCreateParams) error {
	_, err := q.db.ExecContext(ctx, storeItemCreate, arg.StoreID, arg.ItemID)
	return err
}
