// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: stores.sql

package testapp

import (
	"context"
	"database/sql"
	"time"
)

const createStore = `-- name: CreateStore :exec
INSERT INTO goweb.stores (
  name, owner, created_at, updated_at, deleted_at
)
VALUES (
  ?, ?, NOW(), NOW(), NULL
)
`

type CreateStoreParams struct {
	Name  string
	Owner StoresOwner
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) error {
	_, err := q.db.ExecContext(ctx, createStore, arg.Name, arg.Owner)
	return err
}

const getStore = `-- name: GetStore :one
SELECT id, created_at, updated_at, deleted_at, name, owner FROM goweb.stores
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetStore(ctx context.Context, id uint32) (GowebStore, error) {
	row := q.db.QueryRowContext(ctx, getStore, id)
	var i GowebStore
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Owner,
	)
	return i, err
}

const getStoreItems = `-- name: GetStoreItems :one
SELECT i.id, i.created_at, i.updated_at, i.deleted_at, i.name, i.price, i.quantity, i.onsale, s.id
FROM goweb.items i
JOIN goweb.stores_items si ON i.id = si.item_id
JOIN goweb.stores s ON si.store_id = s.id
WHERE s.id = ?
LIMIT 1
`

type GetStoreItemsRow struct {
	ID        uint32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
	Price     float64
	Quantity  uint32
	Onsale    int8
	ID_2      uint32
}

func (q *Queries) GetStoreItems(ctx context.Context, id uint32) (GetStoreItemsRow, error) {
	row := q.db.QueryRowContext(ctx, getStoreItems, id)
	var i GetStoreItemsRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.Onsale,
		&i.ID_2,
	)
	return i, err
}
